<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EGGtCSPlatform.Communication.Tests" />
    <ProjectReference Include="..\EGGtCSPlatform.Communication.Core\EGGtCSPlatform.Communication.Core.csproj" />
  </ItemGroup>
</Project>
