// <auto-generated />
using System;
using EGGtCSPlatform.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGGtCSPlatform.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910120000_AddSimulationMetadata")]
    partial class AddSimulationMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ApplicationSessionEntity",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAtUtc").HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastHeartbeatAtUtc").HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSessions", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.EegFileEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CleanedAtUtc").HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("TEXT");

                    b.Property<Guid>("ExperimentRunId").HasColumnType("TEXT");

                    b.Property<int>("Format").HasColumnType("INTEGER");

                    b.Property<int>("Location").HasColumnType("INTEGER");

                    b.Property<string>("Path").IsRequired().HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes").HasColumnType("INTEGER");

                    b.Property<long?>("SourceFileId").HasColumnType("INTEGER");

                    b.Property<int>("State").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentRunId");

                    b.HasIndex("Path");

                    b.HasIndex("SourceFileId");

                    b.ToTable("EegFiles", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentElectrodeEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<int?>("AcquisitionPhysicalChannelId").HasColumnType("INTEGER");

                    b.Property<int>("AcquisitionUsage").HasColumnType("INTEGER");

                    b.Property<long>("ExperimentId").HasColumnType("INTEGER");

                    b.Property<bool>("IsStimulus").HasColumnType("INTEGER");

                    b.Property<string>("SiteId").IsRequired().HasColumnType("TEXT");

                    b.Property<int?>("StimulationPhysicalChannelId").HasColumnType("INTEGER");

                    b.Property<string>("StimulationRole").HasColumnType("TEXT");

                    b.Property<int?>("TargetDisplayOrder").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId", "SiteId").IsUnique();

                    b.ToTable("ExperimentElectrodes", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentEntity",
                b =>
                {
                    b.Property<string>("SimulationJson").HasColumnType("TEXT");
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("TEXT");

                    b.Property<string>("ExperimentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("OperatorId").HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledAt").HasColumnType("TEXT");

                    b.Property<int>("Status").HasColumnType("INTEGER");

                    b.Property<long>("SubjectId").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentCode").IsUnique();

                    b.HasIndex("OperatorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Experiments", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentEventEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<int>("Cycle").HasColumnType("INTEGER");

                    b.Property<int>("EndTimeAccuracy").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc").HasColumnType("TEXT");

                    b.Property<Guid>("ExperimentRunId").HasColumnType("TEXT");

                    b.Property<int>("Kind").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RequestedAtUtc").HasColumnType("TEXT");

                    b.Property<int>("Sequence").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAtUtc").HasColumnType("TEXT");

                    b.Property<int>("Status").HasColumnType("INTEGER");

                    b.Property<double?>("TimelineEndMilliseconds").HasColumnType("REAL");

                    b.Property<double?>("TimelineStartMilliseconds").HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentRunId", "Sequence").IsUnique();

                    b.ToTable("ExperimentEvents", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentIncidentEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<string>("DeviceStopError").HasColumnType("TEXT");

                    b.Property<bool?>("DeviceStopSucceeded").HasColumnType("INTEGER");

                    b.Property<string>("ExceptionType").HasColumnType("TEXT");

                    b.Property<Guid>("ExperimentRunId").HasColumnType("TEXT");

                    b.Property<int>("Kind").HasColumnType("INTEGER");

                    b.Property<string>("Message").IsRequired().HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc").HasColumnType("TEXT");

                    b.Property<string>("Source").IsRequired().HasColumnType("TEXT");

                    b.Property<string>("StackTrace").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentRunId");

                    b.ToTable("ExperimentIncidents", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentRunEntity",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<double>("AcquisitionDurationMilliseconds").HasColumnType("REAL");

                    b.Property<Guid>("ApplicationSessionId").HasColumnType("TEXT");

                    b.Property<double>("BlankingDurationMilliseconds").HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("TEXT");

                    b.Property<int>("CycleCount").HasColumnType("INTEGER");

                    b.Property<long?>("EegDuplicatePacketCount").HasColumnType("INTEGER");

                    b.Property<long?>("EegLateDiscardedPacketCount").HasColumnType("INTEGER");

                    b.Property<long?>("EegLostPacketCount").HasColumnType("INTEGER");

                    b.Property<long?>("EegOutOfOrderPacketCount").HasColumnType("INTEGER");

                    b.Property<bool?>("EegPacketReorderingEnabled").HasColumnType("INTEGER");

                    b.Property<long?>("EegReceivedPacketCount").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAtUtc").HasColumnType("TEXT");

                    b.Property<long>("ExperimentId").HasColumnType("INTEGER");

                    b.Property<string>("InterruptRequestSource").HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("InterruptRequestedAtUtc").HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastHeartbeatAtUtc").HasColumnType("TEXT");

                    b.Property<int>("LastKnownCycle").HasColumnType("INTEGER");

                    b.Property<double>("LastKnownElapsedMilliseconds").HasColumnType("REAL");

                    b.Property<string>("LastKnownStage").HasColumnType("TEXT");

                    b.Property<double>("RecoveryDurationMilliseconds").HasColumnType("REAL");

                    b.Property<int>("Revision").IsConcurrencyToken().HasColumnType("INTEGER");

                    b.Property<string>("RunMode").IsRequired().HasColumnType("TEXT");

                    b.Property<int>("SampleRateHz").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAtUtc").HasColumnType("TEXT");

                    b.Property<int>("Status").HasColumnType("INTEGER");

                    b.Property<double>("StimulationDurationMilliseconds").HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationSessionId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ExperimentRuns", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ImpedanceSnapshotEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<long>("ExperimentId").HasColumnType("INTEGER");

                    b.Property<double?>("KiloOhms").HasColumnType("REAL");

                    b.Property<int>("Kind").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("MeasuredAtUtc").HasColumnType("TEXT");

                    b.Property<bool>("Passed").HasColumnType("INTEGER");

                    b.Property<string>("SiteId").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId", "SiteId", "Kind").IsUnique();

                    b.ToTable("ImpedanceSnapshots", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.OperatorEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled").HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash").IsRequired().HasColumnType("BLOB");

                    b.Property<int>("PasswordIterations").HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordSalt").IsRequired().HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername").IsUnique();

                    b.ToTable("Operators", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusChannelEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<double>("CurrentMilliAmps").HasColumnType("REAL");

                    b.Property<int>("PhysicalChannelId").HasColumnType("INTEGER");

                    b.Property<string>("Role").IsRequired().HasColumnType("TEXT");

                    b.Property<string>("SiteId").IsRequired().HasColumnType("TEXT");

                    b.Property<long>("StimulusTargetId").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StimulusTargetId", "PhysicalChannelId").IsUnique();

                    b.ToTable("StimulusChannels", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusParadigmEntity",
                b =>
                {
                    b.Property<string>("EnvelopeJson").HasColumnType("TEXT");
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<string>("ArrayMode").IsRequired().HasColumnType("TEXT");

                    b.Property<string>("Direction").IsRequired().HasColumnType("TEXT");

                    b.Property<double>("DutyPercent").HasColumnType("REAL");

                    b.Property<long>("ExperimentId").HasColumnType("INTEGER");

                    b.Property<double>("FrequencyHz").HasColumnType("REAL");

                    b.Property<string>("Kind").IsRequired().HasColumnType("TEXT");

                    b.Property<double>("RampSeconds").HasColumnType("REAL");

                    b.Property<string>("ShamMode").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId").IsUnique();

                    b.ToTable("StimulusParadigms", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusTargetEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder").HasColumnType("INTEGER");

                    b.Property<double>("PeakCurrentMilliAmps").HasColumnType("REAL");

                    b.Property<long>("StimulusParadigmId").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StimulusParadigmId");

                    b.ToTable("StimulusTargets", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.SubjectEntity",
                b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("TEXT");

                    b.Property<string>("NormalizedSubjectCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedSubjectCode").IsUnique();

                    b.ToTable("Subjects", (string)null);
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.EegFileEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.ExperimentRunEntity", "ExperimentRun")
                        .WithMany("Files")
                        .HasForeignKey("ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGGtCSPlatform.Persistence.EegFileEntity", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExperimentRun");

                    b.Navigation("SourceFile");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentElectrodeEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.ExperimentEntity", "Experiment")
                        .WithMany("Electrodes")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.OperatorEntity", "Operator")
                        .WithMany("Experiments")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGGtCSPlatform.Persistence.SubjectEntity", "Subject")
                        .WithMany("Experiments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Subject");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentEventEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.ExperimentRunEntity", "ExperimentRun")
                        .WithMany("Events")
                        .HasForeignKey("ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperimentRun");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentIncidentEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.ExperimentRunEntity", "ExperimentRun")
                        .WithMany("Incidents")
                        .HasForeignKey("ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperimentRun");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentRunEntity",
                b =>
                {
                    b.HasOne(
                            "EGGtCSPlatform.Persistence.ApplicationSessionEntity",
                            "ApplicationSession"
                        )
                        .WithMany("Runs")
                        .HasForeignKey("ApplicationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGGtCSPlatform.Persistence.ExperimentEntity", "Experiment")
                        .WithMany("Runs")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationSession");

                    b.Navigation("Experiment");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ImpedanceSnapshotEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.ExperimentEntity", "Experiment")
                        .WithMany("ImpedanceSnapshots")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusChannelEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.StimulusTargetEntity", "StimulusTarget")
                        .WithMany("Channels")
                        .HasForeignKey("StimulusTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StimulusTarget");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusParadigmEntity",
                b =>
                {
                    b.HasOne("EGGtCSPlatform.Persistence.ExperimentEntity", "Experiment")
                        .WithOne("StimulusParadigm")
                        .HasForeignKey(
                            "EGGtCSPlatform.Persistence.StimulusParadigmEntity",
                            "ExperimentId"
                        )
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusTargetEntity",
                b =>
                {
                    b.HasOne(
                            "EGGtCSPlatform.Persistence.StimulusParadigmEntity",
                            "StimulusParadigm"
                        )
                        .WithMany("Targets")
                        .HasForeignKey("StimulusParadigmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StimulusParadigm");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ApplicationSessionEntity",
                b =>
                {
                    b.Navigation("Runs");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentEntity",
                b =>
                {
                    b.Navigation("Electrodes");

                    b.Navigation("ImpedanceSnapshots");

                    b.Navigation("Runs");

                    b.Navigation("StimulusParadigm");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.ExperimentRunEntity",
                b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Files");

                    b.Navigation("Incidents");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.OperatorEntity",
                b =>
                {
                    b.Navigation("Experiments");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusParadigmEntity",
                b =>
                {
                    b.Navigation("Targets");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.StimulusTargetEntity",
                b =>
                {
                    b.Navigation("Channels");
                }
            );

            modelBuilder.Entity(
                "EGGtCSPlatform.Persistence.SubjectEntity",
                b =>
                {
                    b.Navigation("Experiments");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
